# Generated by Django 5.2.5 on 2025-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите chat_id от Telegram",
                max_length=20,
                null=True,
                verbose_name="Укажите chat_id от Telegram",
            ),
        ),
    ]
