# Generated by Django 5.2.5 on 2025-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pleasanthabit",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Общий доступ для привычки"
            ),
        ),
        migrations.AlterField(
            model_name="usefulhabit",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Общий доступ для привычки"
            ),
        ),
    ]
