# Generated by Django 5.2.5 on 2025-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_usefulhabit_last_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefulhabit",
            name="available",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Доступность привычки. (True - привычка выполнялась меньше 7 дней назад, False - привычка выполнялась больше 7 дней назад, None/null - привычка еще не выполнялась)",
                null=True,
            ),
        ),
    ]
