# Generated by Django 5.2.5 on 2025-11-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_usefulhabit_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="pleasanthabit",
            name="name",
            field=models.CharField(
                blank=True, help_text="Название привычки", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="name",
            field=models.CharField(
                blank=True, help_text="Название привычки", max_length=20, null=True
            ),
        ),
    ]
